spring:
  application:
    name: auth-service

  data:
    mongodb:
      host: localhost
      port: 27017

server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33

config:
  jwt:
    secret:
      apiKey: a1b2c3d4e5f6g7h8