version: '3.3'

services:

  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
     - mongodbdata:/data/db
     - mongodbconfig:/data/configdb
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: 'neo4j/admin'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jplugins:/plugins
      - neo4jdata:/data
      - neo4jimport:/import

volumes:
  mongodbdata:
  mongodbconfig:
  neo4jplugins:
  neo4jdata:
  neo4jimport:
  cassandradata: