spring:
  application:
    name: post-service
  data:
    mongodb:
      host: localhost
      port: 27017

server:
  port: 8001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

config:
  jwt:
    secret:
      apiKey: YTFiMmMzZDRlNWY2ZzdoOA==
