spring:
  application:
    name: graph-service

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: admin
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "com.predrag.a.*"
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  cloud:
    stream:
      function:
        definition: processUserEvents
      bindings:
        processUserEvents-in-0:
          destination: users-changed

server:
  port: 8002

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

config:
  jwt:
    secret:
      apiKey: YTFiMmMzZDRlNWY2ZzdoOA==
