spring:
  application:
    name: media-service
  data:
    mongodb:
      host: localhost
      port: 27017
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 20MB

server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

file:
  upload-dir: /Users/predragantanasijevic/Documents/image-storage/
  path:
    prefix: /images

config:
  jwt:
    secret:
      apiKey: YTFiMmMzZDRlNWY2ZzdoOA==